export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  DELIVERY_AGENT_NOT_FOUND: 'DELIVERY_AGENT_NOT_FOUND',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  MENU_ITEM_NOT_FOUND: 'MENU_ITEM_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_AUTH_HEADER: 'INVALID_AUTH_HEADER',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  INVALID_SCOPE: 'INVALID_SCOPE',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  INVALID_PAGINATION: 'INVALID_PAGINATION',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorMessages: Record<ErrorCode, string> = {
  [ErrorCode.VALIDATION_ERROR]: 'Requisição inválida.',
  [ErrorCode.INVALID_CREDENTIALS]: 'Credenciais inválidas.',
  [ErrorCode.USER_NOT_FOUND]: 'Usuário não encontrado.',
  [ErrorCode.EMAIL_ALREADY_REGISTERED]: 'E-mail já cadastrado.',
  [ErrorCode.UNAUTHENTICATED]: 'Sessão expirada ou inválida.',
  [ErrorCode.DELIVERY_NOT_FOUND]: 'Entrega não encontrada.',
  [ErrorCode.ORDER_NOT_FOUND]: 'Pedido não encontrado.',
  [ErrorCode.NOT_FOUND]: 'Recurso não encontrado.',
  [ErrorCode.DELIVERY_AGENT_NOT_FOUND]: 'Entregador não encontrado.',
  [ErrorCode.CART_NOT_FOUND]: 'Carrinho não encontrado.',
  [ErrorCode.MENU_ITEM_NOT_FOUND]: 'Item de menu não encontrado.',
  [ErrorCode.INVALID_TOKEN]: 'Token inválido ou expirado.',
  [ErrorCode.MISSING_TOKEN]: 'Token ausente.',
  [ErrorCode.INVALID_AUTH_HEADER]: 'Cabeçalho de autorização inválido.',
  [ErrorCode.INTERNAL_SERVER_ERROR]: 'Erro interno do servidor.',
  [ErrorCode.RESTAURANT_NOT_FOUND]: 'Restaurante não encontrado.',
  [ErrorCode.CUSTOMER_NOT_FOUND]: 'Cliente não encontrado.',
  [ErrorCode.INVALID_SCOPE]: 'Permissão insuficiente para executar esta ação.',
  [ErrorCode.INVALID_REFRESH_TOKEN]: 'Refresh token inválido.',
  [ErrorCode.REFRESH_TOKEN_REVOKED]: 'Refresh token revogado.',
  [ErrorCode.REFRESH_TOKEN_EXPIRED]: 'Refresh token expirado.',
  [ErrorCode.REFRESH_TOKEN_REQUIRED]: 'Refresh token é obrigatório.',
  [ErrorCode.INVALID_PAGINATION]: 'Parâmetros de paginação inválidos.',
};
